servicecatalog/oscm-dockerbuild

gc-ant/Dockerfile
oscm-gf/Dockerfile
oscm-sles-based/Dockerfile

@kowalczyka, please especially check oscm-gf: I also removed zip because I think it's not needed, but just to make sure.

Sles based common tools

---

oscm-deployer/templates/docker-compose-oscm-syslog.yml.template
oscm-deployer/templates/docker-compose-oscm.yml.template

oscm-deployer: set container restart policy to always

---

oscm-deployer/start.sh
oscm-deployer/templates/env.template

Soc issues

---

oscm-initdb/templates/sample.sql.core.template

Social bookmarks were removed for required GBPR.

Remove social bookmarks

---

prepare.sh

**Do not merge before https://github.com/servicecatalog/oscm/pull/131.**

Align with changes in oscm repository

---

oscm-initdb/start.sh
oscm-initdb/templates/configsettings.properties.core.template
oscm-initdb/templates/hostfqdn.sql.core.template

Fix reporting

---

oscm-identity/start.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/179)

Debug mode for oscm-identity

---

oscm-deployer/templates/var.env.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/181)

Updated description.

---

oscm-deployer/start.sh
oscm-deployer/templates/docker-compose-oscm.yml.template
oscm-identity/Dockerfile
oscm-identity/start.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/182)

SSL configuration of oscm-identity

---

oscm-deployer/templates/var.env.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/186)

use hardcoded user ids

---

oscm-deployer/templates/docker-compose-oscm.yml.template

Remove oscm-identity from docker compose template.

Remove oscm-identity from compose template.

---

oscm-gf/Dockerfile

In this PR:
- Update Apache TomEE version - necessary for swagger-UI integration for oscm-core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/196)

Update Apache TomEE to 7.1.1

---

oscm-initdb/templates/sample.sql.app.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/200)

Wrong supplier credentials in APP

---

oscm-deployer/templates/var.env.template

* Removed unnecessary password settings.
* Added instructions in comments
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/201)

var.env usability

---

oscm-deployer/start.sh
oscm-deployer/templates/var.env.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/207)

Changes related to WS tests

---

oscm-maven/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/208)

Updated maven version

---

oscm-maven/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/209)

Updated maven version (#208)

---

oscm-deployer/start.sh
oscm-deployer/templates/env.template

Build Job http://...:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/366/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/211)

Use FQDN in default key certificates

---

oscm-gf/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/213)

Updated apache-tomee path

---

oscm-maven/Dockerfile

Configuration for running UI tests with chrome driver
http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_OIDC/29/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/218)

UI tests with chrome

---

oscm-deployer/templates/docker-compose-oscm.yml.template

- New port on oscm-identity
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/223)

new port on oscm-identity

---

oscm-initdb/templates/configsettings.properties.core.template

- SSO cleanup of unused configuration settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/222)

SSO cleanup

---

oscm-app/Dockerfile
oscm-core/Dockerfile
oscm-initdb/Dockerfile
prepare.sh

- changes related to log4j library upgrade to version 2
- OSCM Build And Push job - #586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/227)

Log4j update

---

oscm-db/Dockerfile

- path for the postgresql installation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/228)

Updated postgresql download path

---

oscm-initdb/templates/sample.sql.vmware.template

- Fix double insert into db statement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/229)

fix sample data bug

---

oscm-deployer/templates/env.template
oscm-deployer/templates/var.env.template

New version number

---

oscm-deployer/resources/index.html.template
oscm-deployer/resources/proxy.conf.template
oscm-deployer/start.sh
oscm-deployer/templates/docker-compose-proxy.yml.template

- Add new cert directorys like in other containers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/243)

fix cert directory

---

oscm-deployer/resources/proxy.conf.template

- New Proxy Rule
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/246)

add proxy rule for wsdl

---

oscm-deployer/resources/proxy.conf.template

- <enter list of changes here>

format proxy conf

---

oscm-deployer/resources/index.html.template

- Enhanced list of links on proxy index page with descriptions.

Descriptions in oscm-proxy index page.

---

oscm-deployer/resources/proxy.conf.template

- add proxy rule for identity service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/252)

add proxy rule for identity service

---

oscm-deployer/Dockerfile

- convert  files to linux lineending
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/255)

convert files to linux lineending

---

oscm-initdb/templates/configsettings.properties.core.template

- Add config setting for oscm identity service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/256)

Add redirect config setting

---

oscm-bootstrap/Dockerfile

- Add a new bootstrap container to compile bootstrap sources
- [OSCM Build And Push job](http://estessbesci1:8080/job/OSCM_Docker_Build_and_push_test/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/258)

Add bootstrap container 

---

oscm-initdb/start.sh

- Update URLs from given HOST_FQDN
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/260)

Fix APP_BASE_URL for webtests

---

oscm-initdb/Dockerfile
oscm-initdb/templates/configsettings.properties.core.template
oscm-initdb/templates/hostfqdn.sql.core.template

- Fix the marketplace id parameter in redirect URL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/261)

Fix the mId parameter

---

oscm-initdb/start.sh
oscm-initdb/templates/hostfqdn.sql.app.template
oscm-initdb/templates/hostfqdn.sql.core.template

- remove the updateHostFqdn files and method
- [OSCM Build And Push job](http://estessbesci1:8080/view/Docker_OSCM/job/OSCM_Docker_Build_and_push/783/)
- [OSCM Pull And Start job](http://estessbesci1:8080/view/Docker_OSCM/job/OSCM_Docker_pull_and_start/1299/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/263)

refactor init db

---

oscm-core/resources/server.xml

- enable gzip compression
- [OSCM_Integration_Tests_INTERNAL](http://10.140.16.80:8080/job/OSCM_Integration_Tests_INTERNAL/351/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/267)

Task#265 enable gzip compression

---

oscm-initdb/templates/sample.sql.app.template

- Store approval tool settings with approval controller
/Docker_OSCM/job/OSCM_Docker_Build_and_push//223/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/274)

Store settings in approval controller.

---

oscm-initdb/templates/sample.sql.core.template

- fix the bug to update marketplace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/278)

fix update marketplace bug

---

oscm-branding/resources/brandings.conf

- Fix CORS header.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/281)

Add CORS policy header for oscm-branding cross-domain requests

---

oscm-identity/Dockerfile
oscm-identity/start.sh

- Fix bug. Now the Proxy from the var.env is used. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/283)

fix the identity service

---

oscm-birt/start.sh

- Compute birt base url from report engine url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/296)

Fix Birt Port

---

oscm-deployer/templates/docker-compose-proxy.yml.template
oscm-initdb/templates/platformusers.sql.administrator.template

- Allow to unlock the administrator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/303)

unlock admin

---

oscm-deployer/Dockerfile
oscm-deployer/resources/proxy.conf.template
oscm-deployer/start.sh
oscm-deployer/templates/env.template
oscm-deployer/templates/var.env.template
oscm-deployer/templates/var.env.withoutSampleData.template
oscm-initdb/templates/configsettings.properties.app.template
oscm-initdb/templates/configsettings.properties.core.template

- Proxy starts out of the box
- config settings URLs are now configurable via var.env
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/297)

Fix config settings

---

oscm-deployer/start.sh

- fix integration tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/308)

fix integration tests

---

oscm-birt/start.sh

-  Corrected Base URL replacement in start.sh
Later
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/314)

Fix Base URL 

---

oscm-deployer/start.sh

- Create var.env file for proxy within the thirst deployer call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/318)

Create var.env file for proxy within the thirst deployer call

---

oscm-app/start.sh
oscm-birt/start.sh
oscm-core/start.sh
oscm-gf/Dockerfile

- paths including versions updated with symbolic links
- OSCM Build And Push job - #402
- OSCM Pull And Start job - #396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/317)

Replaced jdk path with symlink

---

oscm-birt/start.sh

- Corrected BIRT base URL injection in viewer.properties. 
Not yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/319)

Fix URL handling.

---

oscm-deployer/templates/env.template
oscm-deployer/templates/var.env.template
oscm-deployer/templates/var.env.withoutSampleData.template

- New OSCM version.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/322)

New OSCM version.

---

oscm-deployer/resources/proxy.conf.template

- Fix proxy rule for oscm-rest-api
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/323)

Proxy access for oscm-rest-api

---

README.md

- Updated readme for fix install dir name.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/326)

Use fix install directory name

---

oscm-deployer/start.sh

- use env files for compose network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/327)

Use env. file correct

---

oscm-deployer/start.sh

- Fix install conditionbug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/329)

Fix install condition bug

---

oscm-db/Dockerfile

- Change RHEL version from 6 to 7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/335)

Fix Daily Build

---

oscm-deployer/start.sh

- Fix1: Substitute ${HOST_FQDN} in var.env (nested var.env variables cannot be resolved at runtime).
*Mandatory checks:**
TBD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/341)

Inject HOST_FQDN in var.env

---

oscm-deployer/resources/proxy.conf.template
oscm-deployer/start.sh

- Fixed HOST_FQDN in proxy.conf
Later
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servicecatalog/oscm-dockerbuild/342)

Fixed proxy.conf
